name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: grafana/setup-k6-action@43b9fc21641a76002687994433dd586f56e791b1 # v1
      - name: Run k6 tests
        run: k6 run test.js
